modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="morearmorandweapons"
version="1.1.0"
displayName="更多的防具和武器"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ddjyx"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.morearmorandweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



